name = "yicapital-portal"
main = "worker/worker.js"
compatibility_date = "2026-07-15"
keep_vars = true
workers_dev = true
preview_urls = true

[limits]
cpu_ms = 30000

[[kv_namespaces]]
binding = "YC_KV"
id = "86de64cdbb864a4fb366acf4260165fd"

[[d1_databases]]
binding = "FEEDBACK_DB"
database_name = "yicapital-feedback"
database_id = "f237ed54-98c3-47ad-8000-d063513219eb"

[triggers]
crons = ["* * * * *", "*/2 * * * *", "30 21 * * *", "30 10 * * *"]
